version: '1'
services:
  postgres:
    image: 'postgres:16'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=pass'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 999:999
    links:
      - 'postgres:localhost'

