services:
  postgres:
    image: postgres:16
    container_name: 'java-postgres'
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: postgres
  app:
    image: 'l2ilai/spring-app:0.2'
    container_name: 'java-app'
    env_file:
      - ./.env
    depends_on:
      - postgres
    ports:
      - 999:999


